# Generated by Django 5.2.9 on 2025-12-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-criado_em']},
        ),
    ]
