# Generated by Django 5.2.9 on 2025-12-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
