# Generated by Django 5.2.9 on 2025-12-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorastreio',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Evento de Rastreio', 'verbose_name_plural': 'Eventos de Rastreio'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
